name: GitHub-Activity-Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate the snake animation
        uses: platane/snk@v3
        with:
          github_user_name: 'salmanrahman7'
          color_snake: '#8d43d3'
          color_dots: '#2a3136,#0e4429,#006d32,#26a641,#39d353'
          outputs: dist/github-contribution-grid-snake.svg

      - name: Add a dark background to the SVG
        run: |
          sed -i '1s/^/<svg xmlns="http:\/\/www.w3.org\/2000\/svg" width="940" height="120" style="background-color: #1f2428;">/' dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
