name: GitHub-Activity-Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: platane/snk@v3
        with:
          github_user_name: 'salmanrahman7'
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: '#8d43d3'
          color_dots: '#2a3136,#0e4429,#006d32,#26a641,#39d353'

      - name: Fix permissions and add background to SVG
        run: |
          # Set write permissions on the SVG file
          chmod +w dist/github-contribution-grid-snake.svg
          # Add the background color to the <svg> tag
          sed -i 's/<svg/<svg style="background-color:#1f2428"/' dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
