name: GitHub-Activity-Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: platane/snk@v3
        with:
          github_user_name: 'salmanrahman7'
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: '#8d43d3'
          color_dots: '#2a3136,#0e4429,#006d32,#26a641,#39d353'
          # Note: We are no longer using color_bg here as we'll set it below

      - name: Add Dark Background to SVG
        uses: kazuya-b/svg-background-action@v1
        with:
          svg_path: dist/github-contribution-grid-snake.svg
          color: "#1f2428"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
