name: GitHub-Activity-Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v3
        with:
          github_user_name: 'salmanrahman7'

          # Custom color configuration to match your desired image
          # The background color
          color_bg: '#1f2428' 

          # The colors for the contribution squares (from level 0 to 4)
          color_dots: '#2a3136,#0e4429,#006d32,#26a641,#39d353'

          # The color of the snake
          color_snake: '#8d43d3' 

          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
